// <auto-generated />
namespace Clothing_v2._2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class realName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(realName));
        
        string IMigrationMetadata.Id
        {
            get { return "201705171939065_realName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
